# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-21 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bosses',
            fields=[
                ('firstName', models.CharField(default='', max_length=200)),
                ('lastName', models.CharField(default='', max_length=200)),
                ('buisnessName', models.CharField(default='', max_length=200)),
                ('photoAGCSPath', models.CharField(default='', max_length=200)),
                ('place', models.CharField(default='', max_length=200)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('bossID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusyEvent',
            fields=[
                ('start_date', models.DateTimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_date', models.DateTimeField(help_text='Final time', verbose_name='Final time')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
                ('eventID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('discription', models.CharField(default='', max_length=2048)),
                ('occupationFieldListString', models.CharField(default='', max_length=2048)),
                ('wage', models.FloatField(default=29.12)),
                ('place', models.CharField(default='', max_length=200)),
                ('nWorkers', models.IntegerField(default=1)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('jobID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('bossID', models.ForeignKey(db_column='userID', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Bosses')),
            ],
        ),
        migrations.CreateModel(
            name='NotficationMessages',
            fields=[
                ('to', models.CharField(default='', max_length=256)),
                ('messageID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(default='sent', max_length=256)),
                ('JobID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Jobs')),
            ],
        ),
        migrations.CreateModel(
            name='UserFirebaseDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fireBaseUser', models.CharField(max_length=200)),
                ('localUser', models.CharField(max_length=200)),
                ('localPassword', models.CharField(max_length=50)),
                ('userID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('occupationFieldListString', models.CharField(default='', max_length=2048)),
                ('firstName', models.CharField(default='', max_length=200)),
                ('lastName', models.CharField(default='', max_length=200)),
                ('photoAGCSPath', models.CharField(default='', max_length=200)),
                ('place', models.CharField(default='', max_length=200)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('wage', models.FloatField(default=29.12)),
                ('workerID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('userID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notficationmessages',
            name='workerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Workers'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='workerID_authorized',
            field=models.ManyToManyField(related_name='workerID_authorized', to='polls.Workers'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='workerID_hired',
            field=models.ManyToManyField(related_name='workerID_hired', to='polls.Workers'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='workerID_responded',
            field=models.ManyToManyField(related_name='workerID_responded', to='polls.Workers'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='workerID_sentNotification',
            field=models.ManyToManyField(related_name='workerID_sentNotification', to='polls.Workers'),
        ),
    ]
