# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-22 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bosses',
            fields=[
                ('firstName', models.CharField(default=b'', max_length=200)),
                ('lastName', models.CharField(default=b'', max_length=200)),
                ('buisnessName', models.CharField(default=b'', max_length=200)),
                ('photoAGCSPath', models.CharField(default=b'', max_length=200)),
                ('place', models.CharField(default=b'', max_length=200)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('bossID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusyEvent',
            fields=[
                ('start_date', models.DateTimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_date', models.DateTimeField(help_text='Final time', verbose_name='Final time')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
                ('eventID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('discription', models.CharField(default=b'', max_length=2048)),
                ('occupationFieldListString', models.CharField(default=b'', max_length=2048)),
                ('wage', models.FloatField(default=29.12)),
                ('place', models.CharField(default=b'', max_length=200)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('jobID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('bossID', models.OneToOneField(db_column=b'userID', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Bosses')),
            ],
        ),
        migrations.CreateModel(
            name='UserFirebaseDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fireBaseUser', models.CharField(max_length=200)),
                ('localUser', models.CharField(max_length=200)),
                ('localPassword', models.CharField(max_length=50)),
                ('userID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('occupationFieldListString', models.CharField(default=b'', max_length=2048)),
                ('firstName', models.CharField(default=b'', max_length=200)),
                ('lastName', models.CharField(default=b'', max_length=200)),
                ('photoAGCSPath', models.CharField(default=b'', max_length=200)),
                ('place', models.CharField(default=b'', max_length=200)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('radius', models.FloatField(default=0.1)),
                ('wage', models.FloatField(default=29.12)),
                ('workerID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('userID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='workerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Workers'),
        ),
    ]
