# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userToken', models.CharField(max_length=200)),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('start_time', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.TimeField(help_text='Final time', verbose_name='Final time')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
            ],
        ),
        migrations.CreateModel(
            name='UserFirebaseDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fireBaseUser', models.CharField(max_length=200)),
                ('localUser', models.CharField(max_length=200)),
                ('localPassword', models.CharField(max_length=50)),
                ('userID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupationFieldListString', models.CharField(max_length=2048)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('portrait', models.ImageField(default=b'content/portraits/no-portrait.png', upload_to=b'')),
                ('localUser', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('radius', models.FloatField()),
                ('minWage', models.IntegerField()),
                ('userID', models.CharField(max_length=200)),
            ],
        ),
    ]
