# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='localUser',
        ),
        migrations.AddField(
            model_name='busyevent',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfirebasedb',
            name='userID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workers',
            name='firstName',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='lastName',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='workers',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='workers',
            name='minWage',
            field=models.FloatField(default=29.12),
        ),
        migrations.AlterField(
            model_name='workers',
            name='occupationFieldListString',
            field=models.CharField(default=b'', max_length=2048),
        ),
        migrations.AlterField(
            model_name='workers',
            name='radius',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='workers',
            name='userID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
