# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupationFieldListString', models.CharField(max_length=2048)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('portrait', models.ImageField(default=b'content/portraits/no-portrait.png', upload_to=b'')),
                ('localUser', models.CharField(max_length=200)),
            ],
        ),
    ]
