# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180622_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='portrait',
        ),
        migrations.AddField(
            model_name='workers',
            name='photoAGCSPath',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
